---
- name: Log into private registry and force re-authorization
  docker_login:
    registry: "{{ docker_registry }}"
    username: "{{ docker_registry_user }}"
    password: "{{ docker_registry_pass }}"
    reauthorize: yes

- name: run ovn domain service with DB 
  docker_compose:
    project_name: ovn-domain-service
    definition:
      services:
        postgres:
          image: postgres
          network_mode: "host"
          environment:
            POSTGRES_PASSWORD: "mysecretpassword"
            PGUSER: "postgres"
          healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 1s
            timeout: 60s
            retries: 5
            start_period: 5s
        ovndb:
          image: "{{ ovndb_image }}"
          network_mode: "host"
          privileged: true
          healthcheck:
            test: ["CMD", "ovn-nbctl", "--db=tcp:0.0.0.0:6641", "list", "NB_global"]
            interval: 1s
            timeout: 60s
            retries: 5
            start_period: 5s
        ovn-domain-service:
          image: "{{ ovn_domain_service_image }}"
          network_mode: "host"
          environment:
            DB_HOST: "127.0.0.1"
            OVNNB_ENDPOINT: "tcp:127.0.0.1:6641"
          depends_on:
            postgres:
              condition: service_healthy
            ovndb:
              condition: service_healthy
