---
- name: Update web servers
  hosts: cloud
  remote_user: root

  tasks:
  - name: install docker py 
    ansible.builtin.pip:
      name: docker-py>=1.7.0
      executable: pip3

  - name: install docker compose
    ansible.builtin.pip:
      name: docker-compose>=1.7.0
      executable: pip3

  - name: run postgres
    docker_container:
      name: ut-postgres
      image: postgres
      ports:
        - 5432:5432
      env:
        POSTGRES_PASSWORD=mysecretpassword
