---
- name: Get running containers
  docker_host_info:
    containers: yes
  register: docker_info

- name: Stop and Remove running containers
  docker_container:
    name: "{{ item }}"
    state: absent
  loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

- name: delete OVS bridges
  openvswitch.openvswitch.openvswitch_bridge: bridge="{{item.name}}" state="{{item.state}}" timeout={{ovs_timeout}}
  loop:
    - { name: "br-int",           state: "absent" }
    - { name: "{{bridge_name}}",  state: "absent" }