---
- name: cleanup ovn isolation
  hosts: cloud
  remote_user: root

  tasks:
  - name: install docker
    ansible.builtin.pip:
      name: docker
      executable: pip3

  - name: stop ovn-fake-multinode
    ansible.builtin.shell: |
      cd /root/work/ovn-fake-multinode
      ./ovn_cluster.sh stop
  
  - name: Get running containers
    docker_host_info:
      containers: yes
    register: docker_info

  - name: Stop and Remove running containers
    docker_container:
      name: "{{ item }}"
      state: absent
    loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
