---
- name: cleanup ovn isolation
  hosts: cloud
  remote_user: root

  tasks:
  - name: install docker
    ansible.builtin.pip:
      name: docker
      executable: pip3

  - name: stop ovn-fake-multinode
    ansible.builtin.shell: |
      cd /root/work/ovn-fake-multinode
      ./ovn_cluster.sh stop
  
  - name: Stop docker containers
    ansible.builtin.shell: docker stop $(docker ps -aq)

  - name: Remove docker containers
    ansible.builtin.shell: docker rm $(docker ps -aq)
